travis:
  secure:
    BINSTAR_TOKEN: CEyWVikFoBqbe1bL65LZAhU8r/45Ky2RaoXbvjeTFEXZCeHP6hNyiUKGvRnKE5a72iAdEXjWTYUqQi3iRBlMDYCiTV5GUR0NIcwahZY/ziQ9217LYb1FrgXz966vSSVjtRPwWuXFuDzWGfV9IzfcdpTecASCHbTw39ma9J9ixUGAicDwzssP/mjbPi8SqOAk5yEzM+0OwRtHZR8VLiEKlTiDLI8quurqUdlaBrH8hjzP3qEfEmfs4DFsxkQW00ab4scFff05tlpi4JxUN3oCx4mPTXA9dbXpQ3Mu4kg/CpdfzYxDMoyfQ4gs9DdxCYkDnO/ZgGegxsOifofJbc7jKUC5+kyjiXFS7MQUgV3ZcScgPJWlxIZvkxngI6KoWQ2xC3QQnH7XCXWLWJasS/euB0+8traJQ6iHEMQlTkR9VrmgcQ5JjZl4GvSl4ErD1SkZY4aJiCKab6rVNhl2OzgIxf4Y/l69dEggdrRuFNeX7Jq0DFasoLW7e//JZPuVByTNU1onVrd3uhFW0SUezApc3PB6R/aYH+A90m3qQgNPrt9RW7K9ZzEL5QbOAVKJGywSz775CBpRouED49h0ovmD3oiSn9Z9Qln05MhYQ/zNJLTCqnTbvnX+KCht3DA/ux/sYG9WH7NRnbGVqWRtSbwOwcuo+Dr1V1wJRtz3f61bnoE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
